<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="GraphicsEngines\G_2D\**" />
    <Compile Remove="GraphicsEngines\TextBased\ScreenElements\**" />
    <EmbeddedResource Remove="GraphicsEngines\G_2D\**" />
    <EmbeddedResource Remove="GraphicsEngines\TextBased\ScreenElements\**" />
    <None Remove="GraphicsEngines\G_2D\**" />
    <None Remove="GraphicsEngines\TextBased\ScreenElements\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="8.0.8" />
  </ItemGroup>

</Project>
